project_id = "rzpgtiqrbijrebktbebf"

[functions.process-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.process-subscription]
verify_jwt = true

[functions.process-commission]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = true