project_id = "rzpgtiqrbijrebktbebf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://rzpgtiqrbijrebktbebf.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.process-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.process-commission]
verify_jwt = false

[functions.process-subscription]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = false

[functions.verify-bank-account]
verify_jwt = false