// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzpgtiqrbijrebktbebf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cGd0aXFyYmlqcmVia3RiZWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjk4NDUsImV4cCI6MjA3MTc0NTg0NX0.VRHEWfET8UflnvUdOcSBdKZNmW1sFaVe4ZM6i6W3DXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});